name: Pint

on: [ push, pull_request ]

jobs:
    pint:
        runs-on: ubuntu-latest

        name: Pint

        steps:
            -   uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    coverage: none

            -   name: Install dependencies
                run: composer install --no-interaction --prefer-dist

            -   name: Run Pint
                run: vendor/bin/pint --test
